#!/bin/sh
# See zig-musl-cc for the -Wl,--version intercept rationale.
if [ $# -eq 1 ] && [ "$1" = "-Wl,--version" ]; then
    echo "LLD 15.0.0 (compatible with GNU linkers)"
    exit 0
fi
exec zig c++ -target x86_64-linux-musl "$@"
